### ISSUE TITLE
Pftool will not build with marfs on REHL 7

### ISSUE THREAD

**Issue by cadejager** [pftool/pftool#65]
I have been trying to get pftool to build on REHL 7/centos 7. I already started making changes in the branch dej_test and can build it now without marfs enabled.

With marfs enabled I cannot get configure to find libmarfs despite the path being defined in LDFLAGS.

I get the following error in the config.log:
```
/usr/bin/ld: /users/dejager/src//marfs/libmarfs.a(mdal.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/lib64/libdl.so.2: error adding symbols: DSO missing from command line
```

**Comment by thewacokid** [comment]
Could try adding "-ldl" to the LDFLAGS.

**Comment by cadejager** [comment]
This has been fixed in the rehl7_support branch

**Comment by jti-lanl** [comment]
Working fine in 1.10
